### ISSUE TITLE
Shouldn't use $exists in query

### ISSUE THREAD

**Issue by vladar** [doctrine/mongodb-odm-softdelete#1]
I've noticed, that $exists is used to query deleted / not deleted entries.

Mongodb documentation states that "exists" cannot use index (http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-%24exists)

Maybe it's worth to use other strategy for querying?

**Comment by jwage** [comment]
Hmm. I am not sure what other strategy could be used. Any ideas?

**Comment by vladar** [comment]
As I see you already changed it to null / $gt checks. Cool, thanks.
