### ISSUE TITLE
Version tags for repository

### ISSUE THREAD

**Issue by TomiS** [doctrine/mongodb-odm-softdelete#12]
Please add version tags for this repository. Just to make it easier to manage dependencies properly

Please... :)

**Comment by TomiS** [comment]
Hi @jmikola or someone... Wouldn't want to push it but it's only like two console commands :) I'd do it but I don't know your versioning policy.

**Comment by jmikola** [comment]
I'll have to defer to @jwage on this. I've merged a few PR's, but I'm really not supporting this library as I am for ODM. Based on its [composer.json](https://github.com/doctrine/mongodb-odm-softdelete/blob/master/composer.json) file, I'm can't say what version of ODM it's compatible with -- it would be foolish to tag it while the dependency is `*`.

**Comment by TomiS** [comment]
@jmikola Oh, I see, sorry, I just picked your name quite randomly from the list :) 

I didn't even notice the problem with composer.json as we're currently using this with Symfony 2.0, but I see what you mean. We've been using it in with ODM version `1.0.0-BETA5`, if that's any help.

Let's hope @jwage has time to check this out...
