### ISSUE TITLE
Old packagist version

### ISSUE THREAD

**Issue by Gnucki** [doctrine/mongodb-odm-softdelete#15]
Hi,

It seems the last commit has not been updated in packagist.

**Comment by jmikola** [comment]
There is no Packagist hook defined for this repository.

@jwage, @kriswallsmith: Do either of you want to add one?

**Comment by kuborgh-mspindelhirn** [comment]
There is a packagist entry for mongodb-odm-softdelete but it points to an outdated fork.

https://packagist.org/packages/doctrine/mongodb-odm-softdelete

You can add this repository in your composer.json to fix this 

```
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/doctrine/mongodb-odm-softdelete"
    }
]
```

**Comment by Gnucki** [comment]
That's what I did of course but I've just wanted to warn.

**Comment by websirnik** [comment]
Asked packagist owner to change the link. Now it points to this repo.
https://packagist.org/packages/doctrine/mongodb-odm-softdelete
